--1. 리스트 불러오기
SELECT A.*, (SELECT ANAME FROM ADMIN WHERE AID=A.AID) ANAME ,(SELECT MNAME FROM MEMBER WHERE MID=A.MID) MNAME , (SELECT MBLACK FROM MEMBER WHERE MID=A.MID) MBLACK
    FROM (SELECT ROWNUM RN, L.* FROM 
    (SELECT * FROM QNA  ORDER BY QGROUP DESC, QSTEP ) L) A
    WHERE RN BETWEEN 1 AND 10;
SELECT QNO, QTITLE, QCONTENT, QGROUP, QPNO, QSTEP, QINDENT, QFILE, QHIT ,QRDATE, QIP, AID, MID, (SELECT ANAME FROM ADMIN WHERE AID=A.AID) ANAME ,(SELECT MNAME FROM MEMBER WHERE MID=A.MID) MNAME 
    FROM (SELECT ROWNUM RN, L.* FROM 
    (SELECT * FROM QNA  ORDER BY QGROUP DESC, QSTEP) L) A
    WHERE RN BETWEEN 1 AND 10;  -- 자바에서 쓸 sql
    
    
SELECT NVL(MIN(QSTEP),0) FROM QNA
   WHERE  QGROUP = 4
   AND QSTEP > 1
   AND QINDENT <= 1;
   
--2-1. 1번이 0 일 경우 

SELECT NVL(MAX(QSTEP),0) + 1 FROM QNA  WHERE QGROUP=4;

INSERT INTO BOARD VALUES 
   (번호, (원글의 qGROUP), (위식값->qstep), (원글의 DEPTH +1) ,' 제목');

--2-2. 1번이 0이 아닐 경우 

UPDATE QNA SET QSTEP = QSTEP + 1 
  WHERE QGROUP =  (원글의 BGROUP)  AND QSTEP >= (1번값);

INSERT INTO QNA VALUES 
   (번호, (원글의 QGROUP), (1번값), (원글의 DEPTH +1) ,' 제목');

 


--1.1 내가 작성한 글목록
SELECT A.*, (SELECT ANAME FROM ADMIN WHERE AID=A.AID) ANAME ,(SELECT MNAME FROM MEMBER WHERE MID=A.MID) MNAME 
    FROM (SELECT ROWNUM RN, L.* FROM 
    (SELECT * FROM QNA  WHERE MID= '관리자1' ORDER BY QNO DESC) L) A
    WHERE RN BETWEEN 1 AND 10;
--2. 글 갯수
SELECT COUNT(*) FROM QNA;
--2.1 내 글갯수
SELECT COUNT(*) FROM QNA WHERE AID='admin1';
--3. 글쓰기
INSERT INTO QNA (QNO ,QTITLE ,QCONTENT,QGROUP ,QFILE ,QIP ,AID, MID)
    VALUES(QNA_SEQ.NEXTVAL, 'TEST', 'TEST', QNA_SEQ.CURRVAL, NULL, '0.0.0.0',NULL,'eee1');
INSERT INTO QNA (QNO ,QTITLE ,QCONTENT,QGROUP ,QFILE ,QIP ,AID, MID)
    VALUES(QNA_SEQ.NEXTVAL, 'TEST', 'TEST', QNA_SEQ.CURRVAL, NULL, '0.0.0.0','admin1',NULL);
--4. hit늘리기
UPDATE QNA SET QHIT = QHIT+1 WHERE QNO=3;
--5. 글 조회(QNO로 DTO가져오기)
SELECT QNO, QTITLE, QCONTENT, QGROUP, QPNO, QSTEP, QINDENT, QFILE, QHIT ,QRDATE, QIP, AID, MID, (SELECT ANAME FROM ADMIN WHERE AID=Q.AID) ANAME,
(SELECT MNAME FROM MEMBER WHERE MID=Q.MID) MNAME,
(SELECT MBLACK FROM MEMBER WHERE MID=Q.MID) MBLACK
FROM QNA Q WHERE QNO=3;
--6. 글 수정
UPDATE QNA SET QTITLE='TEST2', QCONTENT='TESTC', QFILE=NULL, QIP='1.1.1.1' WHERE QNO=4;
--7. 글 삭제
DELETE FROM QNA WHERE QNO=26;
--8. ASTEP QPNO:답변 대상글의QNO, NVL->답변 대상글의 STEP
UPDATE QNA SET QSTEP= QSTEP+1 WHERE QSTEP>NVL((SELECT MAX(QSTEP) FROM QNA WHERE QPNO=20 AND QGROUP=20),3) ;
--8. 답변글
INSERT INTO QNA (QNO ,QTITLE ,QCONTENT,QGROUP ,QSTEP ,QINDENT ,QFILE ,QIP ,QPNO, AID, MID)
    VALUES(QNA_SEQ.NEXTVAL, 'REPLYTEST', 'REPLYTEST', 12, NVL((SELECT MAX(QSTEP) FROM QNA WHERE QPNO=20 AND QGROUP=12),3)+1 , 2+1, NULL, '0.0.0.0',20,'admin1',NULL);
COMMIT;
SELECT TO_CHAR(QRDATE, 'YYYY-MM-DD HH24:MI:SS') FROM QNA WHERE QNO=42;

SELECT Q.*, (SELECT ANAME FROM ADMIN WHERE AID=Q.AID) ANAME ,(SELECT MNAME FROM MEMBER WHERE MID=Q.MID) MNAME  FROM QNA Q WHERE QNO=4;
commit;
select to_char(qrdate, 'yy-mm-dd hh"시" mi"분" ss"초"') from qna;
DELETE FROM QNA;
SELECT * FROM QNA WHERE AID LIKE 'admin%';
