/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-24 07:46:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cookboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cookboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("file:/D:/mega_IT/IDE/apache-tomcat-9.0.30/lib/standard.jar", Long.valueOf(1098678824000L));
    _jspx_dependants.put("jar:file:/D:/mega_IT/IDE/apache-tomcat-9.0.30/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/mega_IT/IDE/apache-tomcat-9.0.30/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/cookboard/list.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tvar keep_cbcNoOption=\"\";\r\n");
      out.write("\tvar keep_order=\"cbNo\";\r\n");
      out.write("\tvar pageNum=1;\r\n");
      out.write("\tvar pageCnt=0;\r\n");
      out.write("\t$('#btn_previous').hide();\r\n");
      out.write("\t$('#btn_next').show();\r\n");
      out.write("\t$('#num1').css({'color': 'white', \r\n");
      out.write("\t\t'background-color': '#f37321',});\r\n");
      out.write("\t//게시판 class별 조회 선택 버튼\r\n");
      out.write("\t//빈칸:전체, 1:알뜰쿠킹, 2:욜로쿠킹\r\n");
      out.write("\t$('.btn_option').bind('click',function(){\r\n");
      out.write("\t\t$('.btn_option').css({'color': 'black', \r\n");
      out.write("\t\t\t'background-color': '#ffbf95',\r\n");
      out.write("\t\t    'border': '2px solid #de8c3d'});\r\n");
      out.write("\t\t$(this).css({'color': 'white', \r\n");
      out.write("\t\t\t'background-color': '#f37321',\r\n");
      out.write("\t\t    'border': '2px solid #e05d09'});\r\n");
      out.write("\t\t$('.btn_page').css({'color': '#f37321', \r\n");
      out.write("\t\t\t'background-color': 'white',});\r\n");
      out.write("\t\t$('#num1').css({'color': 'white', \r\n");
      out.write("\t\t\t'background-color': '#f37321',});\r\n");
      out.write("\t\tvar cbcNoOption = $(this).val();\r\n");
      out.write("\t\tkeep_cbcNoOption = cbcNoOption;\r\n");
      out.write("\t\tvar order = keep_order;\r\n");
      out.write("\t\tkeyword = $('#input_keyword').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/listRecipe.do',\r\n");
      out.write("\t\t\tdataType : 'html',\r\n");
      out.write("\t\t\tdata : \"orderOption=\"+order+\"&cbcNoOption=\"+cbcNoOption+\"&keyword=\"+keyword,\r\n");
      out.write("\t\t\tsuccess : function(data,status){\r\n");
      out.write("\t\t\t\t$('#call_list').html(data);\r\n");
      out.write("\t\t\t\tpageCnt = parseInt($('#pageCnt').val());\r\n");
      out.write("\t\t\t\tif(parseInt(pageNum/10) == parseInt(pageCnt/10)){\r\n");
      out.write("\t\t\t\t\t$('#btn_next').hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('.btn_page' ).each( function() {\r\n");
      out.write("\t\t\t\t\t$(this).show();\r\n");
      out.write("\t\t\t\t\tif(parseInt($(this).attr('value')) > pageCnt){\r\n");
      out.write("\t\t\t\t\t\t$(this).hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t//정렬순 조회 선택 버튼\r\n");
      out.write("\t$('.btn_order').bind('click',function(){\r\n");
      out.write("\t\t$('.btn_order').css({'color': 'black', \r\n");
      out.write("\t\t\t'background-color': '#ffbf95',\r\n");
      out.write("\t\t    'border': '2px solid #de8c3d'});\r\n");
      out.write("\t\t$(this).css({'color': 'white', \r\n");
      out.write("\t\t\t'background-color': '#f37321',\r\n");
      out.write("\t\t    'border': '2px solid #e05d09'});\r\n");
      out.write("\t\t$('.btn_page').css({'color': '#f37321', \r\n");
      out.write("\t\t\t'background-color': 'white',});\r\n");
      out.write("\t\t$('#num1').css({'color': 'white', \r\n");
      out.write("\t\t\t'background-color': '#f37321',});\r\n");
      out.write("\t\tvar order = $(this).val();\r\n");
      out.write("\t\tkeep_order = order;\r\n");
      out.write("\t\tvar cbcNoOption = keep_cbcNoOption;\r\n");
      out.write("\t\tkeyword = $('#input_keyword').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/listRecipe.do',\r\n");
      out.write("\t\t\tdataType : 'html',\r\n");
      out.write("\t\t\tdata : \"orderOption=\"+order+\"&cbcNoOption=\"+cbcNoOption+\"&keyword=\"+keyword,\r\n");
      out.write("\t\t\tsuccess : function(data,status){\r\n");
      out.write("\t\t\t\t$('#call_list').html(data);\r\n");
      out.write("\t\t\t\tpageCnt=parseInt($('#pageCnt').val());\r\n");
      out.write("\t\t\t\tif(parseInt(pageNum/10) == parseInt(pageCnt/10)){\r\n");
      out.write("\t\t\t\t\t$('#btn_next').hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('.btn_page' ).each( function() {\r\n");
      out.write("\t\t\t\t\t$(this).show();\r\n");
      out.write("\t\t\t\t\tif(parseInt($(this).attr('value')) > pageCnt){\r\n");
      out.write("\t\t\t\t\t\t$(this).hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t//이전으로\r\n");
      out.write("\t$('#btn_previous').bind('click',function(){\r\n");
      out.write("\t\tvar order = keep_order;\r\n");
      out.write("\t\tvar cbcNoOption = keep_cbcNoOption;\r\n");
      out.write("\t\tkeyword = $('#input_keyword').val();\r\n");
      out.write("\t\tpageNum = parseInt($('#startPage').val())-1;\r\n");
      out.write("\t\t$('.btn_page').css({'color': '#f37321', \r\n");
      out.write("\t\t\t'background-color': 'white',});\r\n");
      out.write("\t\t$('#num10').css({'color': 'white', \r\n");
      out.write("\t\t\t'background-color': '#f37321',});\r\n");
      out.write("\t\t$('#btn_next').show();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/listRecipe.do',\r\n");
      out.write("\t\t\tdataType : 'html',\r\n");
      out.write("\t\t\tdata : \"orderOption=\"+order+\"&cbcNoOption=\"+cbcNoOption+\"&pageNum=\"+pageNum+\"&keyword=\"+keyword,\r\n");
      out.write("\t\t\tsuccess : function(data,status){\r\n");
      out.write("\t\t\t\t$('#call_list').html(data);\r\n");
      out.write("\t\t\t\tif(pageNum<11){\r\n");
      out.write("\t\t\t\t\t$('#btn_previous').hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$( '.btn_page' ).each( function() {\r\n");
      out.write("\t\t\t\t\tvar temp = parseInt($(this).attr('value'));\r\n");
      out.write("\t\t\t\t\ttemp = temp - 10;\r\n");
      out.write("\t\t\t\t\t$(this).attr('value',temp);\r\n");
      out.write("\t\t\t\t\t$(this).text(temp);\r\n");
      out.write("\t\t\t\t\t$(this).show();\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t//다음으로\r\n");
      out.write("\t$('#btn_next').bind('click',function(){\r\n");
      out.write("\t\tvar order = keep_order;\r\n");
      out.write("\t\tvar cbcNoOption = keep_cbcNoOption;\r\n");
      out.write("\t\tkeyword = $('#input_keyword').val();\r\n");
      out.write("\t\tpageNum = parseInt($('#endPage').val())+1;\r\n");
      out.write("\t\t$('.btn_page').css({'color': '#f37321', \r\n");
      out.write("\t\t\t'background-color': 'white',});\r\n");
      out.write("\t\t$('#num1').css({'color': 'white', \r\n");
      out.write("\t\t\t'background-color': '#f37321',});\r\n");
      out.write("\t\t$('#btn_previous').show();\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/listRecipe.do',\r\n");
      out.write("\t\t\tdataType : 'html',\r\n");
      out.write("\t\t\tdata : \"orderOption=\"+order+\"&cbcNoOption=\"+cbcNoOption+\"&pageNum=\"+pageNum+\"&keyword=\"+keyword,\r\n");
      out.write("\t\t\tsuccess : function(data,status){\r\n");
      out.write("\t\t\t\t$('#call_list').html(data);\r\n");
      out.write("\t\t\t\tpageCnt = parseInt($('#pageCnt').val());\r\n");
      out.write("\t\t\t\tif(parseInt(pageNum/10) == parseInt(pageCnt/10)){\r\n");
      out.write("\t\t\t\t\t$('#btn_next').hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$( '.btn_page' ).each( function() {\r\n");
      out.write("\t\t\t\t\tvar temp = parseInt($(this).attr('value'));\r\n");
      out.write("\t\t\t\t\ttemp = temp + 10;\r\n");
      out.write("\t\t\t\t\t$(this).attr('value',temp);\r\n");
      out.write("\t\t\t\t\t$(this).text(temp);\r\n");
      out.write("\t\t\t\t\tif(parseInt($(this).attr('value')) > pageCnt){\r\n");
      out.write("\t\t\t\t\t\t$(this).hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t//page 숫자 눌렀을 경우 페이지 이동.\r\n");
      out.write("\t$('.btn_page').bind('click',function(){\r\n");
      out.write("\t\tvar order = keep_order;\r\n");
      out.write("\t\tvar cbcNoOption = keep_cbcNoOption;\r\n");
      out.write("\t\tkeyword = $('#input_keyword').val();\r\n");
      out.write("\t\tpageNum = $(this).attr('value');\r\n");
      out.write("\t\t$('.btn_page').css({'color': '#f37321', \r\n");
      out.write("\t\t\t'background-color': 'white',});\r\n");
      out.write("\t\t$('#num'+pageNum).css({'color': 'white', \r\n");
      out.write("\t\t\t'background-color': '#f37321',});\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${conPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/listRecipe.do',\r\n");
      out.write("\t\t\tdataType : 'html',\r\n");
      out.write("\t\t\tdata : \"orderOption=\"+order+\"&cbcNoOption=\"+cbcNoOption+\"&pageNum=\"+pageNum+\"&keyword=\"+keyword,\r\n");
      out.write("\t\t\tsuccess : function(data,status){\r\n");
      out.write("\t\t\t\t$('#call_list').html(data);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar keyword = $('#input_keyword').val();\r\n");
      out.write(" \tif($('#option').val() == 'search_direct'){\r\n");
      out.write(" \t\t$('#btn_option0').trigger('click');\r\n");
      out.write("\t\t$('#btn_cbNo').trigger('click'); \r\n");
      out.write("\t}\r\n");
      out.write(" \tif($('#cbcOption').val()==1){\r\n");
      out.write(" \t\t$('#btn_option1').trigger('click');\r\n");
      out.write(" \t\t$('#btn_cbNo').trigger('click');\r\n");
      out.write(" \t}\r\n");
      out.write(" \tif($('#cbcOption').val()==2){\r\n");
      out.write(" \t\t$('#btn_option2').trigger('click');\r\n");
      out.write(" \t\t$('#btn_cbNo').trigger('click');\r\n");
      out.write(" \t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#option_class {\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\theight: 65px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_option {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-color: #ffbf95;\r\n");
      out.write("\tborder: 2px solid #de8c3d;\r\n");
      out.write("\tpadding: 10px 30px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tborder-radius: 10px 10px 3px 3px;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_order {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-color: #ffbf95;\r\n");
      out.write("\tborder: 2px solid #de8c3d;\r\n");
      out.write("\tpadding: 5px 10px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\tmargin-: 0 2px;\r\n");
      out.write("\tmargin: 0 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_option {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_order {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-top: 33px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 처음 페이지 초기화시 스크립트로 전달할 ajax전송용 파라미터 -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"option\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.option }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"option\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"cbcOption\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cbcOption }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"cbcOption\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"option_class\">\r\n");
      out.write("\t<button class=\"btn_option\" id=\"btn_option0\" value=\"\">전체</button>\r\n");
      out.write("\t<button class=\"btn_option\" id=\"btn_option1\" value=\"1\">알뜰쿠킹</button>\r\n");
      out.write("\t<button class=\"btn_option\" id=\"btn_option2\" value=\"2\">욜로쿠킹</button>\r\n");
      out.write("\t<button class=\"btn_order\" id=\"btn_cbNo\" value=\"cbNo\">최신순</button>\r\n");
      out.write("\t<button class=\"btn_order\" id=\"btn_cbLike\" value=\"cbLike\">추천순</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"call_list\"> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"paging\">\r\n");
      out.write("\t\t<button id=\"btn_previous\" class=\"btn_arrow\" ><</button>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<button id=\"btn_next\" class=\"btn_arrow\" >></button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /cookboard/cookboard.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("conPath");
      // /cookboard/cookboard.jsp(5,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /cookboard/cookboard.jsp(254,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /cookboard/cookboard.jsp(254,2) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1);
      // /cookboard/cookboard.jsp(254,2) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(10);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t<button id=\"num");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn_page\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</button>\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
