SELECT * FROM MEMBER;
ROLLBACK;
COMMIT;
--0. ID 중복CHK
SELECT COUNT(*) FROM MEMBER WHERE MID='AAAA';
--0. NICK 중복CHK
SELECT COUNT(*) FROM MEMBER WHERE MNICK='요리요리'; 
--1. 회원가입
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('CA','AAAA','요리요리','비룡',NULL, NULL, 'default.png');
--2. 로그인
SELECT M.*, GNO, GNAME FROM MEMBER M, GRADE 
WHERE MLIKE BETWEEN GLOW AND GHIGH AND MID='AAAA' AND MPW='AAAA';
SELECT * FROM MEMBER WHERE MID='AAAA' AND MPW='AAAA';

--3. ID로 회원 DTO가져오기(개인정보열람)
SELECT M.*, GNO, GNAME FROM MEMBER M, GRADE 
WHERE MLIKE BETWEEN GLOW AND GHIGH AND MID='aaa1';
--4. 정보수정
UPDATE MEMBER SET MPW='AAAA', MNICK='BBBB', MNAME='안비룡', MTEL='010', MEMAIL='A@COM', MPHOTO=NULL WHERE MID='AAAA';
--5. BLACK
UPDATE MEMBER SET MBLACK= MOD(MBLACK+1,2) WHERE MID='aaa1';
--6. 누적 좋아요 상승
UPDATE MEMBER SET MLIKE= MLIKE + 1 WHERE MID='AAAA';

--7. 회원 목록리스트 가져오기(ID,nick검색)
SELECT * FROM (SELECT ROWNUM RN, A.* FROM 
(SELECT M.*, GNO, GNAME FROM MEMBER M, GRADE 
WHERE MLIKE BETWEEN GLOW AND GHIGH 
AND (MID LIKE '%'||'치'||'%' OR MNICK LIKE '%'||'치'||'%' OR MNAME LIKE '%'||'치'||'%')
ORDER BY MRDATE DESC) A) 
WHERE RN BETWEEN 1 AND 2;
--7.1 회원 카운트
SELECT COUNT(*) FROM MEMBER WHERE MID LIKE '%'||'치'||'%' OR MNICK LIKE '%'||'치'||'%' OR MNAME LIKE '%'||'치'||'%';
--8. 랭킹셰프 목록리스트
SELECT * FROM (SELECT ROWNUM RN, A.* FROM 
(SELECT M.*, GNO, GNAME FROM MEMBER M, GRADE 
WHERE MLIKE BETWEEN GLOW AND GHIGH 
AND GNO=4
ORDER BY MLIKE DESC) A) 
WHERE RN BETWEEN 1 AND 2;
--8.1 랭킹셰프 카운트
SELECT COUNT(*) FROM MEMBER M, GRADE 
WHERE MLIKE BETWEEN GLOW AND GHIGH 
AND GNO=4;



SELECT * FROM MEMBER where MID='aaa1';
UPDATE MEMBER SET MPHOTO='default.png'  ;
ALTER TABLE MEMBER
MODIFY (MNICK VARCHAR2(100) UNIQUE);
commit;
