DROP TABLE NOTICE;
DROP SEQUENCE NOTICE_SEQ;
DROP TABLE QNA;
DROP SEQUENCE QNA_SEQ;
DROP TABLE ADMIN;
DROP TABLE LIKEHISTORY;
DROP SEQUENCE LIKEHISTORY_SEQ;
DROP TABLE COOKBOARDRE;
DROP SEQUENCE COOKBOARDRE_SEQ;
DROP TABLE COOKBOARDDETAIL;
DROP SEQUENCE COOKBOARDDETAIL_SEQ;
DROP TABLE COOKBOARD;
DROP TABLE COOKBOARDCLASS;
DROP SEQUENCE COOKBOARD_SEQ;
DROP TABLE MEMBER;
DROP TABLE GRADE;
CREATE TABLE GRADE(
    GNO NUMBER(2),
    GNAME VARCHAR2(100) NOT NULL,
    GLOW NUMBER(4),
    GHIGH NUMBER(4),
    PRIMARY KEY(GNO)
);
INSERT INTO GRADE VALUES(1,'요리초보',0,9);
INSERT INTO GRADE VALUES(2,'요리수련생',10,49);
INSERT INTO GRADE VALUES(3,'중급셰프',50,99);
INSERT INTO GRADE VALUES(4,'랭킹셰프',100,9999);
CREATE TABLE MEMBER(
    MID VARCHAR2(100),
    MPW VARCHAR2(100) NOT NULL,
    MNICK VARCHAR2(100) NOT NULL,
    MNAME VARCHAR2(100) NOT NULL,
    MTEL VARCHAR2(100),
    MEMAIL VARCHAR2(100),
    MPHOTO VARCHAR2(100) DEFAULT 'default.png',
    MRDATE DATE DEFAULT SYSDATE,
    MBLACK NUMBER(2) DEFAULT 0,
    MLIKE NUMBER(4) DEFAULT 0,
    PRIMARY KEY(MID)
);
CREATE TABLE COOKBOARDCLASS(
    CBCNO NUMBER(4),
    CBCNAME VARCHAR2(30) NOT NULL,
    PRIMARY KEY(CBCNO)
);
INSERT INTO COOKBOARDCLASS VALUES (1, '알뜰쿠킹');
INSERT INTO COOKBOARDCLASS VALUES (2, '욜로쿠킹');
CREATE SEQUENCE COOKBOARD_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE TABLE COOKBOARD(
    CBNO NUMBER(4),
    CBTITLE VARCHAR2(100) NOT NULL,
    CBIMAGE VARCHAR2(100),
    CBINGREDIENT VARCHAR2(300) NOT NULL,
    CBHIT NUMBER(4) DEFAULT 0,
    CBRDATE DATE DEFAULT SYSDATE,
    CBIP VARCHAR2(100) NOT NULL,
    CBCNO NOT NULL,
    MID NOT NULL,
    PRIMARY KEY(CBNO),
    FOREIGN KEY(CBCNO) REFERENCES COOKBOARDCLASS,
    FOREIGN KEY(MID) REFERENCES MEMBER
);
CREATE SEQUENCE COOKBOARDDETAIL_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE TABLE COOKBOARDDETAIL(
    CBDNO NUMBER(8),
    CBDORDER NUMBER(2) NOT NULL,
    CBDIMAGE VARCHAR2(100),
    CBDCONTENT VARCHAR2(1000),
    CBDCOUNT NUMBER(1) NOT NULL,
    CBNO,
    PRIMARY KEY(CBDNO),
    FOREIGN KEY(CBNO) REFERENCES COOKBOARD
);
CREATE SEQUENCE COOKBOARDRE_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE TABLE COOKBOARDRE(
    CBRNO NUMBER(4),
    CBRCONTENT VARCHAR2(1000) NOT NULL,
    CBRIP VARCHAR2(100) NOT NULL,
    CBRRDATE DATE DEFAULT SYSDATE,
    CBNO NOT NULL,
    MID NOT NULL,
    FOREIGN KEY(CBNO) REFERENCES COOKBOARD,
    FOREIGN KEY(MID) REFERENCES MEMBER
);
CREATE SEQUENCE LIKEHISTORY_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE TABLE LIKEHISTORY(
    INO NUMBER(4),
    CBNO NOT NULL,
    MID NOT NULL,
    PRIMARY KEY(INO),
    FOREIGN KEY(CBNO) REFERENCES COOKBOARD,
    FOREIGN KEY(MID) REFERENCES MEMBER
);
CREATE TABLE ADMIN(
    AID VARCHAR2(100),
    APW VARCHAR2(100) NOT NULL,
    ANAME VARCHAR2(100) NOT NULL,
    PRIMARY KEY(AID)
);
INSERT INTO ADMIN VALUES('admin1', '1111', '관리자1');
INSERT INTO ADMIN VALUES('admin2', '2222', '관리자2');
INSERT INTO ADMIN VALUES('admin3', '3333', '관리자3');
CREATE SEQUENCE QNA_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE TABLE QNA(
    QNO NUMBER(4),
    QTITLE VARCHAR2(100) NOT NULL,
    QCONTENT VARCHAR2(1000),
    QGROUP NUMBER(4),
    QSTEP NUMBER(4) DEFAULT 0,
    QINDENT NUMBER(4) DEFAULT 0,
    QFILE VARCHAR2(100),
    QHIT NUMBER(8) DEFAULT 0,
    QRDATE DATE DEFAULT SYSDATE,
    QIP VARCHAR2(100) NOT NULL,
    QPNO NUMBER(4) DEFAULT 0,
    AID,
    MID,
    PRIMARY KEY(QNO),
    FOREIGN KEY(AID) REFERENCES ADMIN,
    FOREIGN KEY(MID) REFERENCES MEMBER
);
CREATE SEQUENCE NOTICE_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE TABLE NOTICE(
    NNO NUMBER(4),
    NTITLE VARCHAR2(100),
    NCONTENT VARCHAR2(1000),
    NHIT NUMBER(8) DEFAULT 0,
    NRDATE DATE DEFAULT SYSDATE,
    AID NOT NULL,
    PRIMARY KEY(NNO),
    FOREIGN KEY(AID) REFERENCES ADMIN
);

COMMIT;