INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa1','111','코커1','김민아','1111', 'a1@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb1','111','타도매클','마미손'	,'1111', 'a1@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc1','111','치즈김밥','사나'		,'1111', 'a1@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd1','111','펭귄','소혜'		,'1111', 'a1@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee1','111','뭐가살쪄','이지은'	,'1111', 'a1@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff1','111','선넘규','장성규'		,'1111', 'a1@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg1','111','아무노래나틀어','지아코','1111', 'a1@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh1','111','뽀로로','펭수'		,'1111', 'a1@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii1','111','소년점프','매드클라운'	,'1111', 'a1@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj1','111','승마클럽회장','Lil Nas X','1111', 'a1@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa2','111','코커2','김민아','1112', 'a2@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb2','111','타도매클','마미손'	,'1112', 'a2@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc2','111','치즈김밥','사나'		,'1112', 'a2@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd2','111','펭귄','소혜'		,'1112', 'a2@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee2','111','뭐가살쪄','이지은'	,'1112', 'a2@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff2','111','선넘규','장성규'		,'1112', 'a2@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg2','111','아무노래나틀어','지아코','1112', 'a2@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh2','111','뽀로로','펭수'		,'1112', 'a2@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii2','111','소년점프','매드클라운'	,'1112', 'a2@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj2','111','승마클럽회장','Lil Nas X','1112', 'a2@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa3','111','코커3','김민아','1113', 'a3@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb3','111','타도매클','마미손'	,'1113', 'a3@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc3','111','치즈김밥','사나'		,'1113', 'a3@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd3','111','펭귄','소혜'		,'1113', 'a3@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee3','111','뭐가살쪄','이지은'	,'1113', 'a3@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff3','111','선넘규','장성규'		,'1113', 'a3@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg3','111','아무노래나틀어','지아코','1113', 'a3@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh3','111','뽀로로','펭수'		,'1113', 'a3@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii3','111','소년점프','매드클라운'	,'1113', 'a3@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj3','111','승마클럽회장','Lil Nas X','1113', 'a3@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa4','111','코커4','김민아','1114', 'a4@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb4','111','타도매클','마미손'	,'1114', 'a4@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc4','111','치즈김밥','사나'		,'1114', 'a4@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd4','111','펭귄','소혜'		,'1114', 'a4@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee4','111','뭐가살쪄','이지은'	,'1114', 'a4@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff4','111','선넘규','장성규'		,'1114', 'a4@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg4','111','아무노래나틀어','지아코','1114', 'a4@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh4','111','뽀로로','펭수'		,'1114', 'a4@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii4','111','소년점프','매드클라운'	,'1114', 'a4@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj4','111','승마클럽회장','Lil Nas X','1114', 'a4@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa5','111','코커5','김민아','1115', 'a5@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb5','111','타도매클','마미손'	,'1115', 'a5@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc5','111','치즈김밥','사나'		,'1115', 'a5@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd5','111','펭귄','소혜'		,'1115', 'a5@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee5','111','뭐가살쪄','이지은'	,'1115', 'a5@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff5','111','선넘규','장성규'		,'1115', 'a5@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg5','111','아무노래나틀어','지아코','1115', 'a5@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh5','111','뽀로로','펭수'		,'1115', 'a5@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii5','111','소년점프','매드클라운'	,'1115', 'a5@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj5','111','승마클럽회장','Lil Nas X','1115', 'a5@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa6','111','코커6','김민아','1116', 'a6@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb6','111','타도매클','마미손'	,'1116', 'a6@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc6','111','치즈김밥','사나'		,'1116', 'a6@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd6','111','펭귄','소혜'		,'1116', 'a6@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee6','111','뭐가살쪄','이지은'	,'1116', 'a6@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff6','111','선넘규','장성규'		,'1116', 'a6@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg6','111','아무노래나틀어','지아코','1116', 'a6@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh6','111','뽀로로','펭수'		,'1116', 'a6@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii6','111','소년점프','매드클라운'	,'1116', 'a6@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj6','111','승마클럽회장','Lil Nas X','1116', 'a6@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa7','111','코커7','김민아','1117', 'a7@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb7','111','타도매클','마미손'	,'1117', 'a7@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc7','111','치즈김밥','사나'		,'1117', 'a7@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd7','111','펭귄','소혜'		,'1117', 'a7@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee7','111','뭐가살쪄','이지은'	,'1117', 'a7@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff7','111','선넘규','장성규'		,'1117', 'a7@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg7','111','아무노래나틀어','지아코','1117', 'a7@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh7','111','뽀로로','펭수'		,'1117', 'a7@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii7','111','소년점프','매드클라운'	,'1117', 'a7@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj7','111','승마클럽회장','Lil Nas X','1117', 'a7@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa8','111','코커8','김민아','1118', 'a8@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb8','111','타도매클','마미손'	,'1118', 'a8@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc8','111','치즈김밥','사나'		,'1118', 'a8@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd8','111','펭귄','소혜'		,'1118', 'a8@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee8','111','뭐가살쪄','이지은'	,'1118', 'a8@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff8','111','선넘규','장성규'		,'1118', 'a8@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg8','111','아무노래나틀어','지아코','1118', 'a8@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh8','111','뽀로로','펭수'		,'1118', 'a8@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii8','111','소년점프','매드클라운'	,'1118', 'a8@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj8','111','승마클럽회장','Lil Nas X','1118', 'a8@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa9','111','코커9','김민아','1119', 'a9@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb9','111','타도매클','마미손'	,'1119', 'a9@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc9','111','치즈김밥','사나'		,'1119', 'a9@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd9','111','펭귄','소혜'		,'1119', 'a9@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee9','111','뭐가살쪄','이지은'	,'1119', 'a9@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff9','111','선넘규','장성규'		,'1119', 'a9@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg9','111','아무노래나틀어','지아코','1119', 'a9@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh9','111','뽀로로','펭수'		,'1119', 'a9@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii9','111','소년점프','매드클라운'	,'1119', 'a9@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj9','111','승마클럽회장','Lil Nas X','1119', 'a9@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa10','111','코커10','김민아','11110', 'a10@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb10','111','타도매클','마미손'	,'11110', 'a10@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc10','111','치즈김밥','사나'		,'11110', 'a10@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd10','111','펭귄','소혜'		,'11110', 'a10@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee10','111','뭐가살쪄','이지은'	,'11110', 'a10@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff10','111','선넘규','장성규'		,'11110', 'a10@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg10','111','아무노래나틀어','지아코','11110', 'a10@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh10','111','뽀로로','펭수'		,'11110', 'a10@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii10','111','소년점프','매드클라운'	,'11110', 'a10@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj10','111','승마클럽회장','Lil Nas X','11110', 'a10@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa11','111','코커11','김민아','11111', 'a11@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb11','111','타도매클','마미손'	,'11111', 'a11@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc11','111','치즈김밥','사나'		,'11111', 'a11@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd11','111','펭귄','소혜'		,'11111', 'a11@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee11','111','뭐가살쪄','이지은'	,'11111', 'a11@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff11','111','선넘규','장성규'		,'11111', 'a11@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg11','111','아무노래나틀어','지아코','11111', 'a11@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh11','111','뽀로로','펭수'		,'11111', 'a11@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii11','111','소년점프','매드클라운'	,'11111', 'a11@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj11','111','승마클럽회장','Lil Nas X','11111', 'a11@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa12','111','코커12','김민아','11112', 'a12@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb12','111','타도매클','마미손'	,'11112', 'a12@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc12','111','치즈김밥','사나'		,'11112', 'a12@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd12','111','펭귄','소혜'		,'11112', 'a12@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee12','111','뭐가살쪄','이지은'	,'11112', 'a12@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff12','111','선넘규','장성규'		,'11112', 'a12@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg12','111','아무노래나틀어','지아코','11112', 'a12@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh12','111','뽀로로','펭수'		,'11112', 'a12@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii12','111','소년점프','매드클라운'	,'11112', 'a12@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj12','111','승마클럽회장','Lil Nas X','11112', 'a12@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa13','111','코커13','김민아','11113', 'a13@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb13','111','타도매클','마미손'	,'11113', 'a13@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc13','111','치즈김밥','사나'		,'11113', 'a13@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd13','111','펭귄','소혜'		,'11113', 'a13@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee13','111','뭐가살쪄','이지은'	,'11113', 'a13@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff13','111','선넘규','장성규'		,'11113', 'a13@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg13','111','아무노래나틀어','지아코','11113', 'a13@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh13','111','뽀로로','펭수'		,'11113', 'a13@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii13','111','소년점프','매드클라운'	,'11113', 'a13@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj13','111','승마클럽회장','Lil Nas X','11113', 'a13@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa14','111','코커14','김민아','11114', 'a14@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb14','111','타도매클','마미손'	,'11114', 'a14@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc14','111','치즈김밥','사나'		,'11114', 'a14@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd14','111','펭귄','소혜'		,'11114', 'a14@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee14','111','뭐가살쪄','이지은'	,'11114', 'a14@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff14','111','선넘규','장성규'		,'11114', 'a14@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg14','111','아무노래나틀어','지아코','11114', 'a14@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh14','111','뽀로로','펭수'		,'11114', 'a14@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii14','111','소년점프','매드클라운'	,'11114', 'a14@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj14','111','승마클럽회장','Lil Nas X','11114', 'a14@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa15','111','코커15','김민아','11115', 'a15@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb15','111','타도매클','마미손'	,'11115', 'a15@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc15','111','치즈김밥','사나'		,'11115', 'a15@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd15','111','펭귄','소혜'		,'11115', 'a15@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee15','111','뭐가살쪄','이지은'	,'11115', 'a15@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff15','111','선넘규','장성규'		,'11115', 'a15@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg15','111','아무노래나틀어','지아코','11115', 'a15@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh15','111','뽀로로','펭수'		,'11115', 'a15@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii15','111','소년점프','매드클라운'	,'11115', 'a15@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj15','111','승마클럽회장','Lil Nas X','11115', 'a15@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa16','111','코커16','김민아','11116', 'a16@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb16','111','타도매클','마미손'	,'11116', 'a16@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc16','111','치즈김밥','사나'		,'11116', 'a16@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd16','111','펭귄','소혜'		,'11116', 'a16@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee16','111','뭐가살쪄','이지은'	,'11116', 'a16@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff16','111','선넘규','장성규'		,'11116', 'a16@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg16','111','아무노래나틀어','지아코','11116', 'a16@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh16','111','뽀로로','펭수'		,'11116', 'a16@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii16','111','소년점프','매드클라운'	,'11116', 'a16@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj16','111','승마클럽회장','Lil Nas X','11116', 'a16@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa17','111','코커17','김민아','11117', 'a17@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb17','111','타도매클','마미손'	,'11117', 'a17@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc17','111','치즈김밥','사나'		,'11117', 'a17@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd17','111','펭귄','소혜'		,'11117', 'a17@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee17','111','뭐가살쪄','이지은'	,'11117', 'a17@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff17','111','선넘규','장성규'		,'11117', 'a17@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg17','111','아무노래나틀어','지아코','11117', 'a17@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh17','111','뽀로로','펭수'		,'11117', 'a17@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii17','111','소년점프','매드클라운'	,'11117', 'a17@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj17','111','승마클럽회장','Lil Nas X','11117', 'a17@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa18','111','코커18','김민아','11118', 'a18@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb18','111','타도매클','마미손'	,'11118', 'a18@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc18','111','치즈김밥','사나'		,'11118', 'a18@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd18','111','펭귄','소혜'		,'11118', 'a18@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee18','111','뭐가살쪄','이지은'	,'11118', 'a18@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff18','111','선넘규','장성규'		,'11118', 'a18@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg18','111','아무노래나틀어','지아코','11118', 'a18@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh18','111','뽀로로','펭수'		,'11118', 'a18@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii18','111','소년점프','매드클라운'	,'11118', 'a18@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj18','111','승마클럽회장','Lil Nas X','11118', 'a18@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa19','111','코커19','김민아','11119', 'a19@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb19','111','타도매클','마미손'	,'11119', 'a19@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc19','111','치즈김밥','사나'		,'11119', 'a19@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd19','111','펭귄','소혜'		,'11119', 'a19@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee19','111','뭐가살쪄','이지은'	,'11119', 'a19@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff19','111','선넘규','장성규'		,'11119', 'a19@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg19','111','아무노래나틀어','지아코','11119', 'a19@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh19','111','뽀로로','펭수'		,'11119', 'a19@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii19','111','소년점프','매드클라운'	,'11119', 'a19@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj19','111','승마클럽회장','Lil Nas X','11119', 'a19@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa20','111','코커20','김민아','11120', 'a20@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb20','111','타도매클','마미손'	,'11120', 'a20@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc20','111','치즈김밥','사나'		,'11120', 'a20@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd20','111','펭귄','소혜'		,'11120', 'a20@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee20','111','뭐가살쪄','이지은'	,'11120', 'a20@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff20','111','선넘규','장성규'		,'11120', 'a20@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg20','111','아무노래나틀어','지아코','11120', 'a20@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh20','111','뽀로로','펭수'		,'11120', 'a20@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii20','111','소년점프','매드클라운'	,'11120', 'a20@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj20','111','승마클럽회장','Lil Nas X','11120', 'a20@com', 'oldtown.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('aaa21','111','코커21','김민아','11121', 'a21@com', '김민아.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('bbb21','111','타도매클','마미손'	,'11121', 'a21@com', '마미손.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ccc21','111','치즈김밥','사나'		,'11121', 'a21@com', '사나.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ddd21','111','펭귄','소혜'		,'11121', 'a21@com', '소혜.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('eee21','111','뭐가살쪄','이지은'	,'11121', 'a21@com', '아이유.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('fff21','111','선넘규','장성규'		,'11121', 'a21@com', '장성규.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('ggg21','111','아무노래나틀어','지아코','11121', 'a21@com', '지아코.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('hhh21','111','뽀로로','펭수'		,'11121', 'a21@com', '펭수.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('iii21','111','소년점프','매드클라운'	,'11121', 'a21@com', '매드클라운.jpg');
INSERT INTO MEMBER (MID, MPW, MNICK, MNAME, MTEL, MEMAIL, MPHOTO) VALUES('jjj21','111','승마클럽회장','Lil Nas X','11121', 'a21@com', 'oldtown.jpg');
COMMIT;
